In [1]:
import os
from dotenv import load_dotenv
import re
import nltk
import json
import pandas as pd
from path import Path
%matplotlib inline
from pandas.io.json import json_normalize
from nltk.sentiment.vader import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()

from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer, PorterStemmer
import nltk
nltk.download('omw-1.4')
import string
from string import punctuation
import re

from collections import Counter
from nltk import ngrams
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import re
import pandas as pd
lemmatizer = WordNetLemmatizer()

from wordcloud import WordCloud
import matplotlib.pyplot as plt
plt.style.use('seaborn-whitegrid')
import matplotlib as mpl
mpl.rcParams['figure.figsize'] = [20.0, 10.0]

import spacy
from spacy import displacy
from pprint import pprint

[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/ameerirfan/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [2]:
load_dotenv()

True

In [3]:
from newsapi import NewsApiClient
api_key = os.getenv("NEWSAPI_KEY")

newsapi = NewsApiClient(api_key=api_key)

# NEWS FOR STOCKS

In [4]:
APPLE_headlines = newsapi.get_everything(q='AAPL',
                                        language="en",
                                       sort_by="relevancy")

with open('AAPL.json', 'w') as json_file:
    json.dump(APPLE_headlines, json_file)

In [5]:
SAMSUNG_headlines = newsapi.get_everything(q='SAMSUNG',
                                        language="en",
                                       sort_by="relevancy")

with open('SMSN.IL.json', 'w') as json_file:
    json.dump(SAMSUNG_headlines, json_file)

In [6]:
TESLA_headlines = newsapi.get_everything(q='TSLA',
                                        language="en",
                                       sort_by="relevancy")

with open('TSLA.json', 'w') as json_file:
    json.dump(TESLA_headlines, json_file)

In [7]:
AMAZON_headlines = newsapi.get_everything(q='AMZN',
                                        language="en",
                                       sort_by="relevancy")

with open('AMZN.json', 'w') as json_file:
    json.dump(AMAZON_headlines, json_file)

In [8]:
MICROSOFT_headlines = newsapi.get_everything(q='MSFT',
                                        language="en",
                                       sort_by="relevancy")

with open('MSFT.json', 'w') as json_file:
    json.dump(MICROSOFT_headlines, json_file)

# NEWS FOR CRYPTO

In [9]:
BITCOIN_headlines = newsapi.get_everything(q='BITCOIN',
                                        language="en",
                                       sort_by="relevancy")

with open('BTC.json', 'w') as json_file:
    json.dump(BITCOIN_headlines, json_file)

In [10]:
ETHERIUM_headlines = newsapi.get_everything(q='ETHERIUM',
                                        language="en",
                                       sort_by="relevancy")

with open('ETH.json', 'w') as json_file:
    json.dump(ETHERIUM_headlines, json_file)

In [11]:
DOGECOIN_headlines = newsapi.get_everything(q='DOGECOIN',
                                        language="en",
                                       sort_by="relevancy")

with open('DOGE.json', 'w') as json_file:
    json.dump(DOGECOIN_headlines, json_file)

In [12]:
SOLANA_headlines = newsapi.get_everything(q='SOLANA',
                                        language="en",
                                       sort_by="relevancy")

with open('SOL.json', 'w') as json_file:
    json.dump(SOLANA_headlines, json_file)

In [13]:
CARDANO_headlines = newsapi.get_everything(q='CARDANO',
                                        language="en",
                                       sort_by="relevancy")

with open('ADA.json', 'w') as json_file:
    json.dump(CARDANO_headlines, json_file)

# Sentiment Article Analysis

##### STOCK ARTICLE SENTIMENT

In [14]:
APPLE_news = pd.read_json ('/Users/ameerirfan/Desktop/FT-BTC-Activities/Project 2/AAPL.json')

df_APPLE = json_normalize(APPLE_news['articles'])

df_APPLE = df_APPLE.drop(['author', 'title', 'url','urlToImage','publishedAt','content','source.id','source.name'], axis=1)

sentiment_title = df_APPLE.apply(lambda x : analyzer.polarity_scores(x['description']), axis=1)

df_APPLE['Comp'] =sentiment_title.apply(lambda x : x.get('compound') )
df_APPLE['Pos'] =sentiment_title.apply(lambda x : x.get('pos') )
df_APPLE['Neu'] =sentiment_title.apply(lambda x : x.get('neu') )
df_APPLE['Neg'] =sentiment_title.apply(lambda x : x.get('neg') )
df_APPLE

/var/folders/n4/gpv7p5n93k529lgh_r2dcw4h0000gn/T/ipykernel_4038/542510695.py:3: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  df_APPLE = json_normalize(APPLE_news['articles'])

,description,Comp,Pos,Neu,Neg
0,It's been a good summer for equities in genera...,0.7261,0.202,0.798,0.000
1,Ireland's data privacy regulator has agreed to...,0.4404,0.109,0.891,0.000
2,China's brutal heatwave is now hurting major p...,-0.7783,0.000,0.595,0.405
3,Apple is still a relatively small player in th...,0.0000,0.000,1.000,0.000
4,"In a clash of industry titans, which one comes...",0.0000,0.000,1.000,0.000
...,...,...,...,...,...
95,These two beaten-down stocks ought to deliver ...,0.0000,0.000,1.000,0.000
96,"Bear markets can be unnerving, but they're als...",0.3612,0.152,0.848,0.000
97,The new bill targeted at lowering inflation ha...,0.2500,0.150,0.750,0.100
98,Demand for the handheld devices has been relia...,-0.1280,0.000,0.903,0.097
99,Investors were spooked by comments made by the...,0.0000,0.000,1.000,0.000

In [15]:
SAMSUNG_news = pd.read_json ('/Users/ameerirfan/Desktop/FT-BTC-Activities/Project 2/SMSN.IL.json')

df_SAMSUNG = json_normalize(SAMSUNG_news['articles'])

df_SAMSUNG = df_SAMSUNG.drop(['author', 'title', 'url','urlToImage','publishedAt','content','source.id','source.name'], axis=1)

sentiment_title = df_SAMSUNG.apply(lambda x : analyzer.polarity_scores(x['description']), axis=1)

df_SAMSUNG['Comp'] =sentiment_title.apply(lambda x : x.get('compound') )
df_SAMSUNG['Pos'] =sentiment_title.apply(lambda x : x.get('pos') )
df_SAMSUNG['Neu'] =sentiment_title.apply(lambda x : x.get('neu') )
df_SAMSUNG['Neg'] =sentiment_title.apply(lambda x : x.get('neg') )
df_SAMSUNG

/var/folders/n4/gpv7p5n93k529lgh_r2dcw4h0000gn/T/ipykernel_4038/3861086390.py:3: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  df_SAMSUNG = json_normalize(SAMSUNG_news['articles'])

,description,Comp,Pos,Neu,Neg
0,"Throughout its first three generations, Samsun...",0.8402,0.250,0.750,0.000
1,"Earlier this year, the first gaming monitor wi...",0.9393,0.302,0.698,0.000
2,Samsung's 32-inch Smart Monitor M8 can act not...,0.9556,0.328,0.672,0.000
3,"At this point, Samsung has a lot of experience...",0.4215,0.064,0.936,0.000
4,We're starting to see Samsung's Gaming Hub pop...,0.2023,0.039,0.961,0.000
...,...,...,...,...,...
95,The Z Flip 4's new software takes advantage of...,0.2500,0.154,0.846,0.000
96,You're looking to buy a mid-range phone. Shoul...,0.0000,0.000,1.000,0.000
97,"Samsung and Google have both introduced new ""P...",0.0000,0.000,1.000,0.000
98,The 55-inch 4K Samsung Odyssey Ark monitor is ...,0.5574,0.161,0.839,0.000
99,Who says you need to pay for perfection? With ...,0.6486,0.218,0.728,0.054

In [16]:
TESLA_news = pd.read_json ('/Users/ameerirfan/Desktop/FT-BTC-Activities/Project 2/TSLA.json')

df_TESLA = json_normalize(TESLA_news['articles'])

df_TESLA = df_TESLA.drop(['author', 'title', 'url','urlToImage','publishedAt','content','source.id','source.name'], axis=1)

sentiment_title = df_TESLA.apply(lambda x : analyzer.polarity_scores(x['description']), axis=1)

df_TESLA['Comp'] =sentiment_title.apply(lambda x : x.get('compound') )
df_TESLA['Pos'] =sentiment_title.apply(lambda x : x.get('pos') )
df_TESLA['Neu'] =sentiment_title.apply(lambda x : x.get('neu') )
df_TESLA['Neg'] =sentiment_title.apply(lambda x : x.get('neg') )
df_TESLA

/var/folders/n4/gpv7p5n93k529lgh_r2dcw4h0000gn/T/ipykernel_4038/3191502574.py:3: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  df_TESLA = json_normalize(TESLA_news['articles'])

,description,Comp,Pos,Neu,Neg
0,China's brutal heatwave is now hurting major p...,-0.7783,0.000,0.595,0.405
1,A potential contract with FedEx has Ford share...,0.1531,0.068,0.932,0.000
2,Rideshare and delivery giant Uber (NASDAQ: UBE...,-0.1027,0.000,0.945,0.055
3,"Instances, where Wall Street and WallStreetBet...",0.6808,0.211,0.789,0.000
4,Social media company Twitter (TWTR) has been e...,-0.7717,0.045,0.712,0.243
...,...,...,...,...,...
95,31 August 2022 Alliance Trust PLC TRANSACTION ...,0.8602,0.293,0.707,0.000
96,"Oslo, 1 September 2022 AS Torinitamar, which i...",0.2960,0.087,0.913,0.000
97,Seligson & Co Fund Management Company PlcSTOCK...,0.0000,0.000,1.000,0.000
98,The company said new license requirements prev...,0.1818,0.102,0.898,0.000
99,ProVen VCT plc Transaction in own shares1 Sept...,0.2960,0.084,0.916,0.000

In [17]:
AMAZON_news = pd.read_json ('/Users/ameerirfan/Desktop/FT-BTC-Activities/Project 2/AMZN.json')

df_AMAZON = json_normalize(AMAZON_news['articles'])

df_AMAZON = df_AMAZON.drop(['author', 'title', 'url','urlToImage','publishedAt','content','source.id','source.name'], axis=1)

sentiment_title = df_AMAZON.apply(lambda x : analyzer.polarity_scores(x['description']), axis=1)

df_AMAZON['Comp'] =sentiment_title.apply(lambda x : x.get('compound') )
df_AMAZON['Pos'] =sentiment_title.apply(lambda x : x.get('pos') )
df_AMAZON['Neu'] =sentiment_title.apply(lambda x : x.get('neu') )
df_AMAZON['Neg'] =sentiment_title.apply(lambda x : x.get('neg') )
df_AMAZON

/var/folders/n4/gpv7p5n93k529lgh_r2dcw4h0000gn/T/ipykernel_4038/734534947.py:3: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  df_AMAZON = json_normalize(AMAZON_news['articles'])

,description,Comp,Pos,Neu,Neg
0,California's attorney general sued Amazon on W...,-0.8176,0.044,0.720,0.237
1,"In 2019, Wegmans, the cult-favorite northeaste...",-0.1027,0.000,0.958,0.042
2,A man evicted from a Houston apartment buildin...,-0.7783,0.000,0.772,0.228
3,<ol><li>Rumors Of Amazon Buyout That Have Sinc...,-0.5574,0.041,0.829,0.129
4,"In a clash of industry titans, which one comes...",0.0000,0.000,1.000,0.000
...,...,...,...,...,...
95,Watch all of the highlights between the Dallas...,0.0000,0.000,1.000,0.000
96,Listen on the go! A daily podcast of Wall Stre...,0.0000,0.000,1.000,0.000
97,What's the best way to invest in tech stocks r...,0.7430,0.249,0.751,0.000
98,Downing Strategic Micro-Cap Investment Trust P...,0.8176,0.321,0.679,0.000
99,31 August 2022 HARGREAVE HALE AIM VCT PLC NAV ...,0.5994,0.154,0.846,0.000

In [18]:
MICROSOFT_news = pd.read_json ('/Users/ameerirfan/Desktop/FT-BTC-Activities/Project 2/MSFT.json')

df_MICROSOFT = json_normalize(MICROSOFT_news['articles'])

df_MICROSOFT = df_MICROSOFT.drop(['author', 'title', 'url','urlToImage','publishedAt','content','source.id','source.name'], axis=1)

sentiment_title = df_MICROSOFT.apply(lambda x : analyzer.polarity_scores(x['description']), axis=1)

df_MICROSOFT['Comp'] =sentiment_title.apply(lambda x : x.get('compound') )
df_MICROSOFT['Pos'] =sentiment_title.apply(lambda x : x.get('pos') )
df_MICROSOFT['Neu'] =sentiment_title.apply(lambda x : x.get('neu') )
df_MICROSOFT['Neg'] =sentiment_title.apply(lambda x : x.get('neg') )
df_MICROSOFT

/var/folders/n4/gpv7p5n93k529lgh_r2dcw4h0000gn/T/ipykernel_4038/172669022.py:3: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  df_MICROSOFT = json_normalize(MICROSOFT_news['articles'])

,description,Comp,Pos,Neu,Neg
0,Software giant Microsoft (MSFT) reported robus...,0.3400,0.076,0.924,0.000
1,Tech giant International Business Machines (IB...,0.8834,0.339,0.661,0.000
2,Avaya Holdings (AVYA) recently announced the e...,0.0000,0.000,1.000,0.000
3,Although the software industry has been strugg...,0.1027,0.124,0.794,0.082
4,While concerns over the Fed's hawkish stance h...,-0.2960,0.000,0.929,0.071
...,...,...,...,...,...
95,Their recent subpar performance doesn't reflec...,0.0000,0.000,1.000,0.000
96,The Australian Competition & Consumer Commissi...,-0.2263,0.000,0.929,0.071
97,Microsoft's (MSFT) planned $69 billion purchas...,0.0000,0.000,1.000,0.000
98,Microsoft's (MSFT) planned $69 billion acquisi...,0.0772,0.053,0.947,0.000
99,Saudi Arabia's sovereign wealth fund took a st...,0.4939,0.127,0.873,0.000

##### CRYPTO ARTICLE SENTIMENT

In [19]:
BITCOIN_news = pd.read_json ('/Users/ameerirfan/Desktop/FT-BTC-Activities/Project 2/BTC.json')

df_BITCOIN = json_normalize(BITCOIN_news['articles'])

df_BITCOIN = df_BITCOIN.drop(['author', 'title', 'url','urlToImage','publishedAt','content','source.id','source.name'], axis=1)

sentiment_title = df_BITCOIN.apply(lambda x : analyzer.polarity_scores(x['description']), axis=1)

df_BITCOIN['Comp'] =sentiment_title.apply(lambda x : x.get('compound') )
df_BITCOIN['Pos'] =sentiment_title.apply(lambda x : x.get('pos') )
df_BITCOIN['Neu'] =sentiment_title.apply(lambda x : x.get('neu') )
df_BITCOIN['Neg'] =sentiment_title.apply(lambda x : x.get('neg') )
df_BITCOIN

/var/folders/n4/gpv7p5n93k529lgh_r2dcw4h0000gn/T/ipykernel_4038/3786982742.py:3: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  df_BITCOIN = json_normalize(BITCOIN_news['articles'])

,description,Comp,Pos,Neu,Neg
0,One of the most influential cryptocurrency pro...,0.4927,0.197,0.803,0.000
1,"Bitcoin was off 1.63% at $19,920 by late after...",0.0000,0.000,1.000,0.000
2,"Cryptocurrencies fell sharply on Friday, with ...",-0.2732,0.000,0.851,0.149
3,"For years, ether could barely dream of challen...",0.2601,0.145,0.855,0.000
4,"Ethereum, which currently uses as much energy ...",0.2732,0.139,0.861,0.000
...,...,...,...,...,...
95,Men allegedly tried to extort hundreds of thou...,-0.4767,0.061,0.810,0.129
96,A Wednesday Wall Street Journal article sugges...,0.0000,0.000,1.000,0.000
97,Want to buy bitcoin without the middleman? Pax...,0.0772,0.106,0.894,0.000
98,Former Oracle employees describe how the cloud...,0.3612,0.102,0.898,0.000
99,Both the Metaverse and DeFi are set for vastly...,0.0000,0.000,1.000,0.000

In [20]:
ETHERIUM_news = pd.read_json ('/Users/ameerirfan/Desktop/FT-BTC-Activities/Project 2/ETH.json')

df_ETHERIUM = json_normalize(ETHERIUM_news['articles'])

df_ETHERIUM = df_ETHERIUM.drop(['author', 'title', 'url','urlToImage','publishedAt','content','source.id','source.name'], axis=1)

sentiment_title = df_ETHERIUM.apply(lambda x : analyzer.polarity_scores(x['description']), axis=1)

df_ETHERIUM['Comp'] =sentiment_title.apply(lambda x : x.get('compound') )
df_ETHERIUM['Pos'] =sentiment_title.apply(lambda x : x.get('pos') )
df_ETHERIUM['Neu'] =sentiment_title.apply(lambda x : x.get('neu') )
df_ETHERIUM['Neg'] =sentiment_title.apply(lambda x : x.get('neg') )
df_ETHERIUM

/var/folders/n4/gpv7p5n93k529lgh_r2dcw4h0000gn/T/ipykernel_4038/1559168172.py:3: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  df_ETHERIUM = json_normalize(ETHERIUM_news['articles'])

,description,Comp,Pos,Neu,Neg
0,Graphics card maker Nvidia is also feeling the...,-0.2732,0.073,0.851,0.076
1,Other inventions include a humane insect remov...,0.4767,0.099,0.858,0.043
2,This week also marks the beginning of the MERG...,0.0000,0.000,1.000,0.000
3,Comment on this storyCommentThe crypto world h...,0.0000,0.000,1.000,0.000
4,Skybridge Capital CEO Anthony Scaramucci says ...,0.3182,0.071,0.929,0.000
5,"Trading Coin Terminal (TT), a blockchain platf...",0.1280,0.061,0.939,0.000
6,The Merge will lead to the reduction of the Et...,0.8715,0.248,0.752,0.000
7,The Robinhood Investor Index is based on the t...,0.2023,0.049,0.951,0.000
8,"Liquid Meta Capital Holdings Ltd. (""Liquid Met...",0.0000,0.000,1.000,0.000
9,The Merge will lead to the reduction of the Et...,0.7337,0.205,0.795,0.000
10,Bitcoin and Solana continued their rallies in ...,-0.0258,0.000,0.973,0.027
11,"Richard Garriot, the creator of the Ultima ser...",0.0000,0.000,1.000,0.000
12,A side income feels like being rich if you alr...,0.7269,0.253,0.747,0.000
13,"GZIRA, Malta, Sept. 12, 2022 /PRNewswire/ -- C...",0.6597,0.134,0.866,0.000
14,Bitcoin and Ether rallied in late Friday after...,0.6597,0.141,0.859,0.000
15,Cryptocurrency markets continued their skid in...,0.2023,0.042,0.958,0.000
16,The Alien franchise has had an incredibly vari...,0.6249,0.097,0.903,0.000
17,Bitcoin won’t be a hedge against inflation unt...,0.3612,0.060,0.940,0.000
18,My CPU was at 100% usage and I thought that it...,0.2709,0.103,0.839,0.059
19,"Trading Coin Terminal (TT), a blockchain platf...",0.1280,0.038,0.962,0.000
20,My cpu was at 100% usage and I thought that it...,-0.4956,0.098,0.763,0.138
21,"GZIRA, Malta, Sept. 12, 2022 /PRNewswire/ -- C...",0.6597,0.134,0.866,0.000
22,"Stablecoins Survived ‘Crypto Winter,’ But That...",0.2846,0.063,0.937,0.000
23,"TORONTO, Sept. 1, 2022 /PRNewswire/ - Liquid M...",0.3818,0.073,0.927,0.000
24,The crypto world has had a rough summer. That ...,0.7672,0.281,0.719,0.000
25,"It's official, Ethereum is no longer proof of ...",0.2247,0.063,0.893,0.045
26,In honor of the 125th anniversary of the first...,0.7845,0.165,0.835,0.000

In [21]:
DOGECOIN_news = pd.read_json ('/Users/ameerirfan/Desktop/FT-BTC-Activities/Project 2/DOGE.json')

df_DOGECOIN = json_normalize(DOGECOIN_news['articles'])

df_DOGECOIN = df_DOGECOIN.drop(['author', 'title', 'url','urlToImage','publishedAt','content','source.id','source.name'], axis=1)

sentiment_title = df_DOGECOIN.apply(lambda x : analyzer.polarity_scores(x['description']), axis=1)

df_DOGECOIN['Comp'] =sentiment_title.apply(lambda x : x.get('compound') )
df_DOGECOIN['Pos'] =sentiment_title.apply(lambda x : x.get('pos') )
df_DOGECOIN['Neu'] =sentiment_title.apply(lambda x : x.get('neu') )
df_DOGECOIN['Neg'] =sentiment_title.apply(lambda x : x.get('neg') )
df_DOGECOIN

/var/folders/n4/gpv7p5n93k529lgh_r2dcw4h0000gn/T/ipykernel_4038/138617684.py:3: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  df_DOGECOIN = json_normalize(DOGECOIN_news['articles'])

,description,Comp,Pos,Neu,Neg
0,The $258 billion racketeering lawsuit accusing...,-0.2960,0.068,0.783,0.149
1,The Tesla and SpaceX CEO faces even more claim...,0.0000,0.000,1.000,0.000
2,"""He has a tendency to latch onto communities t...",0.0000,0.000,1.000,0.000
3,What does Athens have to do with Jerusalem—and...,0.0000,0.000,1.000,0.000
4,The billionaire Tesla CEO is encouraging his f...,0.5267,0.236,0.764,0.000
...,...,...,...,...,...
95,Some analysts said impending monetary tighteni...,0.3612,0.122,0.878,0.000
96,"Bitcoin could slide to “summer lows near $18,7...",-0.2023,0.000,0.847,0.153
97,Is the cryptocurrency gearing up for another e...,0.0000,0.000,1.000,0.000
98,Americans are so accustomed to the standard in...,0.8102,0.261,0.656,0.083
99,A class action suit against Elon Musk has adde...,-0.4404,0.000,0.892,0.108

In [22]:
SOLANA_news = pd.read_json ('/Users/ameerirfan/Desktop/FT-BTC-Activities/Project 2/SOL.json')

df_SOLANA = json_normalize(SOLANA_news['articles'])

df_SOLANA = df_SOLANA.drop(['author', 'title', 'url','urlToImage','publishedAt','content','source.id','source.name'], axis=1)

sentiment_title = df_SOLANA.apply(lambda x : analyzer.polarity_scores(x['description']), axis=1)

df_SOLANA['Comp'] =sentiment_title.apply(lambda x : x.get('compound') )
df_SOLANA['Pos'] =sentiment_title.apply(lambda x : x.get('pos') )
df_SOLANA['Neu'] =sentiment_title.apply(lambda x : x.get('neu') )
df_SOLANA['Neg'] =sentiment_title.apply(lambda x : x.get('neg') )
df_SOLANA

/var/folders/n4/gpv7p5n93k529lgh_r2dcw4h0000gn/T/ipykernel_4038/2226392747.py:3: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  df_SOLANA = json_normalize(SOLANA_news['articles'])

,description,Comp,Pos,Neu,Neg
0,Derivatives-focused decentralized finance (DeF...,-0.6249,0.000,0.859,0.141
1,Look who misunderstood the consequences a Sola...,-0.4404,0.050,0.822,0.127
2,Solana and OSOM announce an upcoming smartphon...,-0.1280,0.000,0.951,0.049
3,Gameplay Galaxy has announced a new round of f...,0.0000,0.000,1.000,0.000
4,Blockchain experts call Ethereum's merge the m...,0.4927,0.198,0.802,0.000
...,...,...,...,...,...
95,These “permissionless pools'' don't have any o...,0.3400,0.130,0.870,0.000
96,Developers cited faster transactions and “high...,0.0000,0.000,1.000,0.000
97,LDH Architectural Design丨Poetry Wine (Solana) ...,0.0000,0.000,1.000,0.000
98,The bitcoin and crypto market is teetering on ...,0.0000,0.000,1.000,0.000
99,Some are predicting the Fed could soon trigger...,0.0000,0.000,1.000,0.000

In [23]:
CARDANO_news = pd.read_json ('/Users/ameerirfan/Desktop/FT-BTC-Activities/Project 2/ADA.json')

df_CARDANO = json_normalize(CARDANO_news['articles'])

df_CARDANO = df_CARDANO.drop(['author', 'title', 'url','urlToImage','publishedAt','content','source.id','source.name'], axis=1)

sentiment_title = df_CARDANO.apply(lambda x : analyzer.polarity_scores(x['description']), axis=1)

df_CARDANO['Comp'] =sentiment_title.apply(lambda x : x.get('compound') )
df_CARDANO['Pos'] =sentiment_title.apply(lambda x : x.get('pos') )
df_CARDANO['Neu'] =sentiment_title.apply(lambda x : x.get('neu') )
df_CARDANO['Neg'] =sentiment_title.apply(lambda x : x.get('neg') )
df_CARDANO

/var/folders/n4/gpv7p5n93k529lgh_r2dcw4h0000gn/T/ipykernel_4038/2179246102.py:3: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  df_CARDANO = json_normalize(CARDANO_news['articles'])

,description,Comp,Pos,Neu,Neg
0,"Bitcoin bounced above $21,000 for the first ti...",0.2960,0.091,0.909,0.000
1,‘The merge’ project will end role of ‘miners’ ...,0.1280,0.063,0.886,0.051
2,"Crypto is still in a bear market, but one exci...",0.9349,0.452,0.548,0.000
3,"The market is in free-fall, as bears pile into...",0.0000,0.000,1.000,0.000
4,Users on the popular online brokerage Robinhoo...,0.4215,0.189,0.811,0.000
...,...,...,...,...,...
95,(Bloomberg) -- Bitcoin nursed a four-day drop ...,-0.7269,0.000,0.764,0.236
96,"Bitcoin fell back below US$20,000 after moving...",-0.3182,0.000,0.913,0.087
97,"Bitcoin and Ether made up some ground, with mo...",0.2023,0.065,0.935,0.000
98,"Bitcoin and Ether fell Monday morning in Asia,...",0.2023,0.070,0.930,0.000
99,Bitcoin and Ether added to morning gains in Tu...,0.5390,0.163,0.837,0.000

# MARKET SENTIMENT ANALYSIS

### STOCK SENTIMENT

In [24]:
AAPL_Sen_Report = df_APPLE.describe()
AAPL_Sen_Report.to_csv("Apple Sentiment Report.csv")

In [25]:
SMSN_Sen_Report = df_SAMSUNG.describe()
SMSN_Sen_Report.to_csv("Samsung Sentiment Report.csv")

In [26]:
TSLA_Sen_Report = df_TESLA.describe()
TSLA_Sen_Report.to_csv("Tesla Sentiment Report.csv")

In [27]:
AMZN_Sen_Report = df_AMAZON.describe()
AMZN_Sen_Report.to_csv("Amazon Sentiment Report.csv")

In [28]:
MSFT_Sen_Report = df_MICROSOFT.describe()
MSFT_Sen_Report.to_csv("Microsoft Sentiment Report.csv")

### CRYPTO SENTIMENT

In [29]:
BTC_Sen_Report = df_BITCOIN.describe()
BTC_Sen_Report.to_csv("Bitcoin Sentiment Report.csv")

In [30]:
ETH_Sen_Report = df_ETHERIUM.describe()
ETH_Sen_Report.to_csv("Etherium Sentiment Report.csv")

In [31]:
DOGE_Sen_Report = df_DOGECOIN.describe()
DOGE_Sen_Report.to_csv("Dogecoin Sentiment Report.csv")

In [34]:
SOL_Sen_Report = df_SOLANA.describe()
SOL_Sen_Report.to_csv("Solana Sentiment Report.csv")

In [35]:
ADA_Sen_Report = df_CARDANO.describe()
ADA_Sen_Report.to_csv("Cardano Sentiment Report.csv")